[workspace]
members = [
    "crates/decay-server",
]

[workspace.dependencies]
tokio = { version = "1.0", features = ["full"] }
warp = { version = "0.3", features = ["tls"] }
log = "0.4"
env_logger = "0.9"

[profile.release]
opt-level = 3
lto = true